import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <meta charset="UTF-8" />
        <link rel="icon" href="/favicon.ico" />
        <script type="stylesheet" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"></script>
        <script type="stylesheet" src="https://unicons.iconscout.com/release/v3.0.6/css/line.css"></script>
      </Head>

      <main>
        <Header title="PRLX ETF - Dashboard" />
        <p className="description">
          Parallax Decentralized Finance
        </p>

        document.write('        ');
        document.write('        <!-- partial:index.partial.html -->');
        document.write('        <aside class="sidebar position-fixed top-0 left-0 overflow-auto h-100 float-left" id="show-side-navigation1">');
        document.write('          <i class="uil-bars close-aside d-md-none d-lg-none" data-close="show-side-navigation1"></i>');
        document.write('          <div class="sidebar-header d-flex justify-content-center align-items-center px-3 py-4">');
        document.write('            <img');
        document.write('                 class="rounded-pill img-fluid"');
        document.write('                 width="65"');
        document.write('                 src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907008/medium/1501685726/enhance"');
        document.write('                 alt="">');
        document.write('            <div class="ms-2">');
        document.write('              <h5 class="fs-6 mb-0">');
        document.write('                <a class="text-decoration-none" href="#">PRLX HODLer</a>');
        document.write('              </h5>');
        document.write('              <p class="mt-1 mb-0">Lorem ipsum dolor sit amet consectetur.</p>');
        document.write('            </div>');
        document.write('          </div>');
        document.write('          <center>');
        document.write('            <button class="connectWallet" onclick="startApp"');
        document.write('            style="background-color:#ffc107; color:#fff; outline:7px solid #313348;');
        document.write('            text-shadow:');
        document.write('            -1px -1px 0 #000,');
        document.write('            1px -1px 0 #000,');
        document.write('            -1px 1px 0 #000,');
        document.write('            1px 1px 0 #000;">&nbsp');
        document.write('            Connect wallet &nbsp</button>');
        document.write('          </center>');
        document.write('');
        document.write('          <div class="search position-relative text-center px-4 py-3 mt-2">');
        document.write('            <input type="text" class="form-control w-100 border-0 bg-transparent" placeholder="Search here">');
        document.write('            <i class="fa fa-search position-absolute d-block fs-6"></i>');
        document.write('          </div>');
        document.write('');
        document.write('          <ul class="categories list-unstyled">');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-estate fa-fw"></i><a href="#"> Dashboard</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="">');
        document.write('              <i class="uil-folder"></i><a href="#"> File Manager</a>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-calendar-alt"></i><a href="#"> Calender</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-envelope-download fa-fw"></i><a href="#"> Mailbox</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-shopping-cart-alt"></i><a href="#"> eCommerce</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-bag"></i><a href="#"> Projects</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="">');
        document.write('              <i class="uil-setting"></i><a href="#"> Settings</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-chart-pie-alt"></i><a href="#"> Components</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="has-dropdown">');
        document.write('              <i class="uil-panel-add"></i><a href="#"> Charts</a>');
        document.write('              <ul class="sidebar-dropdown list-unstyled">');
        document.write('                <li><a href="#">Lorem ipsum</a></li>');
        document.write('                <li><a href="#">ipsum dolor</a></li>');
        document.write('                <li><a href="#">dolor ipsum</a></li>');
        document.write('                <li><a href="#">amet consectetur</a></li>');
        document.write('                <li><a href="#">ipsum dolor sit</a></li>');
        document.write('              </ul>');
        document.write('            </li>');
        document.write('            <li class="">');
        document.write('              <i class="uil-map-marker"></i><a href="#"> Maps</a>');
        document.write('            </li>');
        document.write('          </ul>');
        document.write('        </aside>');
        document.write('');
        document.write('        <section id="wrapper">');
        document.write('          <nav class="navbar navbar-expand-md">');
        document.write('            <div class="container-fluid mx-2">');
        document.write('              <div class="navbar-header">');
        document.write('                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#toggle-navbar" aria-controls="toggle-navbar" aria-expanded="false" aria-label="Toggle navigation">');
        document.write('                  <i class="uil-bars text-white"></i>');
        document.write('                </button>');
        document.write('                <a class="navbar-brand" href="#">Parallax<span class="main-color">DeFi</span></a>');
        document.write('              </div>');
        document.write('              <div class="collapse navbar-collapse" id="toggle-navbar">');
        document.write('                <ul class="navbar-nav ms-auto">');
        document.write('                  <li class="nav-item dropdown">');
        document.write('                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">');
        document.write('                      Settings');
        document.write('                    </a>');
        document.write('                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">');
        document.write('                      <li>');
        document.write('                        <a class="dropdown-item" href="#">My account</a>');
        document.write('                      </li>');
        document.write('                      <li><a class="dropdown-item" href="#">My inbox</a>');
        document.write('                      </li>');
        document.write('                      <li><a class="dropdown-item" href="#">Help</a>');
        document.write('                      </li>');
        document.write('                      <li><hr class="dropdown-divider"></li>');
        document.write('                      <li><a class="dropdown-item" href="#">Log out</a></li>');
        document.write('                    </ul>');
        document.write('                  </li>');
        document.write('                  <li class="nav-item">');
        document.write('                    <a class="nav-link" href="#"><i class="uil-comments-alt"></i><span>23</span></a>');
        document.write('                  </li>');
        document.write('                  <li class="nav-item">');
        document.write('                    <a class="nav-link" href="#"><i class="uil-bell"></i><span>98</span></a>');
        document.write('                  </li>');
        document.write('                  <li class="nav-item">');
        document.write('                    <a class="nav-link" href="#">');
        document.write('                      <i data-show="show-side-navigation1" class="uil-bars show-side-btn"></i>');
        document.write('                    </a>');
        document.write('                  </li>');
        document.write('                </ul>');
        document.write('              </div>');
        document.write('            </div>');
        document.write('          </nav>');
        document.write('');
        document.write('          <div class="p-4">');
        document.write('            <div class="welcome">');
        document.write('              <div class="content rounded-3 p-3">');
        document.write('                <h1 class="fs-3">Welcome to Parallax Finance</h1>');
        document.write('                <p class="mb-0">Hello John Mac! Welcome to your ETF Fund dashboard!</p>');
        document.write('              </div>');
        document.write('            </div>');
        document.write('');
        document.write('            <section class="statistics mt-4">');
        document.write('              <div class="row">');
        document.write('                <div class="col-lg-4">');
        document.write('                  <div class="box d-flex rounded-2 align-items-center mb-4 mb-lg-0 p-3">');
        document.write('                    <i class="uil-envelope-shield fs-2 text-center bg-primary rounded-circle"></i>');
        document.write('                    <div class="ms-3">');
        document.write('                      <div class="d-flex align-items-center">');
        document.write('                        <h3 class="mb-0">1,245</h3> <span class="d-block ms-2">Emails</span>');
        document.write('                      </div>');
        document.write('                      <p class="fs-normal mb-0">Lorem ipsum dolor sit amet</p>');
        document.write('                    </div>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-lg-4">');
        document.write('                  <div class="box d-flex rounded-2 align-items-center mb-4 mb-lg-0 p-3">');
        document.write('                    <i class="uil-file fs-2 text-center bg-danger rounded-circle"></i>');
        document.write('                    <div class="ms-3">');
        document.write('                      <div class="d-flex align-items-center">');
        document.write('                        <h3 class="mb-0">34</h3> <span class="d-block ms-2">Projects</span>');
        document.write('                      </div>');
        document.write('                      <p class="fs-normal mb-0">Lorem ipsum dolor sit amet</p>');
        document.write('                    </div>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-lg-4">');
        document.write('                  <div class="box d-flex rounded-2 align-items-center p-3">');
        document.write('                    <i class="uil-users-alt fs-2 text-center bg-success rounded-circle"></i>');
        document.write('                    <div class="ms-3">');
        document.write('                      <div class="d-flex align-items-center">');
        document.write('                        <h3 class="mb-0">5,245</h3> <span class="d-block ms-2">Users</span>');
        document.write('                      </div>');
        document.write('                      <p class="fs-normal mb-0">Lorem ipsum dolor sit amet</p>');
        document.write('                    </div>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('              </div>');
        document.write('            </section>');
        document.write('');
        document.write('            <section class="charts mt-4">');
        document.write('              <div class="row">');
        document.write('                <div class="col-lg-6">');
        document.write('                  <div class="chart-container rounded-2 p-3">');
        document.write('                    <h3 class="fs-6 mb-3">Daily Volume</h3>');
        document.write('                    <canvas id="myChart"></canvas>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-lg-6">');
        document.write('                  <div class="chart-container rounded-2 p-3">');
        document.write('                    <h3 class="fs-6 mb-3">Market Capitalization</h3>');
        document.write('                    <canvas id="myChart2"></canvas>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('              </div>');
        document.write('            </section>');
        document.write('');
        document.write('            <section class="admins mt-4">');
        document.write('              <div class="row">');
        document.write('                <div class="col-md-6">');
        document.write('                  <div class="box">');
        document.write('                    <!-- <h4>Admins:</h4> -->');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3 mb-4">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148906966/small/1501685402/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Hampus Obama</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3 mb-4">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907137/small/1501685404/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Ukko Heinonen</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907019/small/1501685403/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Warwick Bátori</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-md-6">');
        document.write('                  <div class="box">');
        document.write('                    <!-- <h4>Moderators:</h4> -->');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3 mb-4">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907114/small/1501685404/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Bakir Assendorp</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3 mb-4">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907086/small/1501685404/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Ivaylo Panosyan</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                    <div class="admin d-flex align-items-center rounded-2 p-3">');
        document.write('                      <div class="img">');
        document.write('                        <img class="img-fluid rounded-pill"');
        document.write('                             width="75" height="75"');
        document.write('                             src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907008/medium/1501685726/enhance"');
        document.write('                             alt="admin">');
        document.write('                      </div>');
        document.write('                      <div class="ms-3">');
        document.write('                        <h3 class="fs-5 mb-1">Joge Lucky</h3>');
        document.write('                        <p class="mb-0">Lorem ipsum dolor sit amet consectetur elit.</p>');
        document.write('                      </div>');
        document.write('                    </div>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('              </div>');
        document.write('            </section>');
        document.write('');
        document.write('            <section class="statis mt-4 text-center">');
        document.write('              <div class="row">');
        document.write('                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">');
        document.write('                  <div class="box bg-primary p-3">');
        document.write('                    <i class="uil-eye"></i>');
        document.write('                    <h3>5,154</h3>');
        document.write('                    <p class="lead">Views</p>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">');
        document.write('                  <div class="box bg-danger p-3">');
        document.write('                    <i class="uil-user"></i>');
        document.write('                    <h3>245</h3>');
        document.write('                    <p class="lead">KYC</p>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-md-6 col-lg-3 mb-4 mb-md-0">');
        document.write('                  <div class="box bg-warning p-3">');
        document.write('                    <i class="uil-shopping-cart"></i>');
        document.write('                    <h3>5,154</h3>');
        document.write('                    <p class="lead">Sales</p>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('                <div class="col-md-6 col-lg-3">');
        document.write('                  <div class="box bg-success p-3">');
        document.write('                    <i class="uil-feedback"></i>');
        document.write('                    <h3>5,154</h3>');
        document.write('                    <p class="lead">Transactions</p>');
        document.write('                  </div>');
        document.write('                </div>');
        document.write('              </div>');
        document.write('            </section>');
        document.write('');
        document.write('            <section class="charts mt-4">');
        document.write('              <div class="chart-container p-3">');
        document.write('                <h3 class="fs-6 mb-3">PRLX DeFi Price Chart</h3>');
        document.write('                <div style="height: 300px">');
        document.write('                  <canvas id="chart3" width="100%"></canvas>');
        document.write('                </div>');
        document.write('              </div>');
        document.write('            </section>');
        document.write('          </div>');
        document.write('        </section>');
        document.write('        <!-- partial -->');
        document.write('          <script type="module" src="metaMask.js"></script>');
        document.write('          <script src=\'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.js\'></script>');
        document.write('          <script src=\'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.jshttps://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\'></script><script  src="./script.js"></script>');
        document.write('      ');


        </main>

      <Footer />
    </div>
  )
}
